name: Bot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: BOTMUSIC
    runs-on: ubuntu-latest
    
    steps:
      - name: clone source
        run: |
          git config --global user.email nasutionmiku@gmail.com
          git config --global user.name Shiivam69
          git clone https://Shiivam69:$GH_TOKEN@github.com/Shiivam69/Yukki -b master
          cd Yukki
          curl $CONFIG_FILE_URL -o config.env
        env:
         GH_TOKEN: ${{secrets.GH_TOKEN}}
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          apt-get update -y
          sudo apt-get upgrade -y
          apt-get install python3-pip ffmpeg -y
          pip install -U pip
          apt-get install nodejs -y 
          npm i -g npm
          pip install -U -r requirements.txt
          bash start &
          sleep 300m
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
